### PR TITLE
Translation into ru

### PR DESCRIPTION
**Pull request by Olezha**
There are problems with a copy-paste. These are files content/pages/*-fr.md (they are a copy of the corresponding English files). The main difference between them looks like this: `diff content/pages/contribute.md content/pages/contribute-fr.md`
```
3c3
< lang: en
---
> lang: fr
```
On the one hand, I did not find a way not create such files with Pelican, on the other hand, such language versions of pages are needed, and then I would like to transfer the translation there from file locales/fr/LC_MESSAGES/freenet_site.po

Need help how to do better

### CODE REVIEW

**Comment by ArneBab** [comment]
Hi @Olezha, sorry for only answering now — I only noticed your pull-request now (feel free to ping me on IRC if you file a pull-request in the future and I don’t notice it).

To translate the site, you need to add all the to-be-translated strings in locales/ru/LC_MESSAGES/freenet_site.po — the translated pages are then built from these.

**Comment by Olezha** [comment]
It is technically possible to add all translations to a single file. But logically only general translations, such as the site interface, should be in this file. Each article should be in a separate file, and if there is a translation of this article, then it should also be in a new separate file. The Pelican engine provides for this. I would like to ask you to consider switching to this style of organizing translations. If necessary, I can describe the pros and cons of these approaches.

I also want to ask about the need for "white" SEO optimization of HTML markup. I'm talking about such a markup, when it will be more convenient for search engines to recognize the site and they can make a more beautiful block about the site in the output of search results. If possible, we would like to do it.

**Comment by ArneBab** [comment]
As you can see from the low rate of change on the site, we do not currently have the resources to do a migration to a different approach. We still have leftovers from the previous migration.

There’s not only the site itself, but also transifex integration and communicating the changes to the voluntary translators (and ensuring that they do not have additional work through the integration) that are required for migration.

I’d love seeing preview-image and -text (and similar) changes.

However the biggest block right now is that we need to migrate away from transifex (that stopped its service) and our infrastructure maintainer is currently swamped with work.

**Comment by Olezha** [comment]
I was very careful to change the way the site works now. And I tried only to change something at least. Thus, the French translation (and transifex) remained working as before (using file `locales/fr/LC_MESSAGES/freenet_site.po`).

In the French version of the translation, I came across the translated text, but the one that did not make it to the site. It's on the About page: `diff content/pages/about.md content/pages/about-fr.md`.

However, I added a new, additional translation into ru in a different approach. This should not affect volunteers who have previously done French translation.

Files `content/pages/about-ru.md`, `content/pages/contribute-ru.md`, `content/pages/documentation-ru.md`, `content/pages/donate-ru.html`, `content/pages/download-ru.md`, `content/pages/help-ru.md` and `content/2019-09-09-false-positives-ru.md` almost entirely consist of the translation of the corresponding pages. And file `locales/ru/LC_MESSAGES/freenet_site.po` contains the translation of the interface.

In the screenshots I want to show that the English and French pages continue to work as before, but the translation into ru has been added.

Screenshot 2021-08-05 at 10-13-37 Freenet
Screenshot 2021-08-05 at 10-13-58 Freenet
Screenshot 2021-08-05 at 10-14-04 Freenet
Screenshot 2021-08-05 at 10-14-09 Freenet Project
Screenshot 2021-08-05 at 10-14-15 Freenet Project
Screenshot 2021-08-05 at 10-14-21 Freenet Project

**Pull request merged**
