### PR TITLE
Re-add donation progress bar, improve readability & visibility

### PR DESCRIPTION
**Pull request by xor-freenet**
The code has been designed to allow easily editing the red out in case you think it looks bad.
I'd recommend trying whether there is a pre-defined "orange" in the CSS to replace the red with before totally removing color.

### CODE REVIEW

**Comment by Thynix** [comment]
This is certainly sufficiently legible to fix the problems the small bar had. I don't think what is essentially a `<blink>` tag is appropriate. I'd like to just go with the single large bar across the top of the page with an explicit goal as discussed on IRC:

2015-10-28 19:59:16     @operhiem1      xor-freenet: As far as always having a bar - I think always having something like that is not conducive to fundraising for two reasons: it's always there so people get used to it, and it's filling up a bar without "full" state instead of going for a concrete goal.
2015-10-28 19:59:43     @operhiem1      For that reason I'd prefer having a big bar across the top of the page only when we're raising a years' funding.

**Comment by xor-freenet** [comment]
> it's always there so people get used to it

How often do you visit the websites of self-auto-updating software?
I don't think people visit it often enough to get used to anything.
Besides, the opacity blinking ensures that people see the bar when it is low.

> and it's filling up a bar without "full" state instead of going for a concrete goal.

The concrete goal is 1 year of funding, which is the 100% limit of the bar.

> I'd like to just go with the single large bar across the top of the page with an explicit goal as discussed on IRC.

I am _not_ proposing to not get a small bar.
I am proposing this as an intermediate solution until we have one. Otherwise we lose potential donations every day.
The large bar stuff is more complex to implement and thus will potentially take lots of days = cause us to lose lots of money if we don't merge this now.

> I don't think what is essentially a <blink> tag is appropriate.

Why? We're out of money. People need to notice. A large bar serves the same intention: Forcing people to focus on it. So if we want to force people's focus on donations anyway, we can go for either solution. This is the more easy one for now as the large bar stuff is more complex.

**Comment by Thynix** [comment]
I'll deploy this anyway without the colors or blinking until we have the large bar and news release ready.

**Comment by xor-freenet** [comment]
Thanks. I would really please like you to at least have a look at how the opacity fading actually renders before you ditch it. It really does look neat IMHO. If you want to ditch one of the both measures, would prefer you ditch the red and keep the opacity fading.

**Comment by Thynix** [comment]
I did look at it, yes. I'll keep the red.

**Comment by xor-freenet** [comment]
Thanks. Given that we've spent so much of our time on this unfortunate thing, maybe it might make sense to put 2 versions on the testing server (red and twinkle) and ask people on the mailing list which one they like, or whether they want neither of both :|
(I'd offer to put it on a server myself, but i don't have any.)

**Comment by Thynix** [comment]
Given that this is a temporary thing I'm skeptical how worthwhile it is to solicit input from the mailing list.

Deployed without blinking.

**Comment by xor-freenet** [comment]
Thanks & good night :)

**Pull request merged**
