### PR TITLE
Donation tweaks

### PR DESCRIPTION
**Pull request by Thynix**
This is some polishing of the donation page and donation section on the home page. It asks directly for donations instead of making a statement that we're fundraising, and mentions that we no longer can afford / are hiring developers.

### CODE REVIEW

**Comment by Thynix** [comment]
Now the donation bar looks like this:



and the donation page intro looks like this:

**Comment by bertm** [comment]
I like the rephrasing.

The non-profit text was added only recently for seemingly good reasons. I see how you think it might be distracting, however I do still think it is relevant information (consider for instance the donation matching programme mentioned on the support mailing list).

Would you consider it a good idea to add this info in fine print below the donate button? I envision it would look like this:

>  Freenet Project, Inc. is a 501(c)3 non-profit organization. Donations are tax deductible.

nonprofit

[0001-Add-501-c-3-info-as-fine-print-below-Donate-button.patch](https://github.com/freenet/website/files/40795/0001-Add-501-c-3-info-as-fine-print-below-Donate-button.patch.txt)

**Comment by xor-freenet** [comment]
Heh, your comment on IRC had made me afraid I was going to be completely edited out again, but I'm positively surpised :) Good rephrasing -> ACK.

**Comment by xor-freenet** [comment]
About the non-profit part - how about a tradeoff of keeping it but shortening it as follows:
- Leave out the legal details which are not interesting to anyone who is not a lawyer: "Inc", "501(c)3"
- Also, since "Inc" is gone, we could also just say "Freenet" instead of "Freenet Project".
- "Donations are tax deductible" is only interesting to people who want to deduct taxes, and those will usually know that they are anyway?

So overall, it would be:
"Freenet is a non-profit organization."

**Comment by bertm** [comment]
"Freenet is an organization" is simply not true. Freenet is the main focus
of Freenet Project, Inc. which is in fact an organization in that sense.
There is no such thing as donating towards a project, projects are not
legal entities and don't own bank accounts.

I agree that the 501(c)3 part is unnecessarily legalese, however the tax
deductibility was intended to explain what that actually means for those
who donate (AFAIK, IANAL), as an additional incentive to donate.

**Comment by Thynix** [comment]
"Donations to The Freenet Project, Inc are tax-deductible." ?

**Comment by toad** [comment]
Only for americans?

**Comment by Thynix** [comment]
Is that what that is?

**Comment by Thynix** [comment]
I feel like this is enough that we'll want to add the news entry with more details at the same time behind a `(read more)` link after the top line.

**Comment by bertm** [comment]
A `read more…` link sounds like a great plan.

Tax deductibility is a given for American residents or entities (implied by FPI's _public charity_ status at the IRS), and might be possible (however unlikely) for residents / entities in other countries, depending on local laws. For Canadians it's quite plausible under the [USA – Canada tax convention](http://www.fin.gc.ca/treaties-conventions/USA_-eng.asp) (article XXI, paragraph 6).

**Comment by ArneBab** [comment]
I’m missing a section in People which says “The Freenet Project Board”, linked from the Donations page.

**Comment by Thynix** [comment]
I've added a donation appeal and deployed to https://testing.freenetproject.org/

Anything else?

**Comment by Thynix** [comment]
I'm wondering if two "(read more...)"s is too many. Thoughts on getting rid of the lower one?

**Comment by bertm** [comment]
The first "read more" does not lead to the donations page, nor does its target link to it. I'll try to improve that later today.

**Comment by Thynix** [comment]
Ah, yeah. A "Donate" button (with some introduction) in the news entry could be good as well.

**Comment by bertm** [comment]
What about replacing the first `(read more...)` with a simple `Learn more about our fundraiser.`? This would avoid the duplication and be more informative at the same time.

**Comment by ArneBab** [comment]
@bertm that idea sounds good.

**Comment by bertm** [comment]
I found another approach to work better (at least for me): more imperatively ask the visitor to donate and explain why in one punch line.

An additional `(read more...)` immediately after that makes much more sense than the same after a question.

**Comment by Thynix** [comment]
Deployed.

**Comment by ArneBab** [comment]
thank you!

**Pull request merged**
