### PR TITLE
Replace "corporation" with "organization"

### PR DESCRIPTION
**Pull request by Thynix**
"Corporation" can imply "corporate" and "stuffy" and "rich"; FPI is none
of these. "Organization" is a valid way to refer to a 501(c)(3); the IRS
does it. [0]

[0] https://www.irs.gov/Charities-&-Non-Profits/Charitable-Organizations/Exemption-Requirements-Section-501(c)(3)-Organizations

### CODE REVIEW

**Comment by bertm** [comment]
"Freenet Project, Inc." is the name of the business entity (at least that's how they're registered[0] and file their [990 forms](http://990s.foundationcenter.org/990_pdf_archive/954/954864038/954864038_201312_990EZ.pdf))

I don't think expanding "Inc." adds any value here – those who care already know the meaning of the abbreviation. If anything, we should drop the prefix "The".

I'm all for replacing "corporation"  with "organization" wherever possible, though.

[0] Search for entity number C2326587 at http://kepler.sos.ca.gov/

**Comment by Thynix** [comment]
Whoops, I didn't think to check. Is just the first two ready to deploy,
then?

**Comment by bertm** [comment]
The first two are fine for now.

For the future, it might be a good idea to `grep` the site for different uses of "Freenet", "Freenet [Pp]roject", "([Tt]he )?Freenet Project[,]? Inc[.]?" and so on, and make all of that somewhat more consistent.

**Comment by Thynix** [comment]
Agreed.

**Comment by Thynix** [comment]
First two merged via cherry-pick as d1dc650 and 5f0fbe6.

**Comment by xor-freenet** [comment]
ACK, good catch!
bertm's idea of grepping for more cases sounds like something which should be done. Want me to file a bug?

**Comment by Thynix** [comment]
Sure.

**Pull request closed without merging**
