### PR TITLE
Docs: Crypto key is in the CHK, not in the file

### PR DESCRIPTION
**Pull request by sur5r**

### CODE REVIEW

**Comment by Thynix** [comment]
Oh, good catch. Hm, "The decryption key is stored encrypted within the key"
isn't right either. What about something like "the decryption key is part
of the key for the file, and is not included in requests for the file's
pieces,"?

**Comment by sur5r** [comment]
Ah, true. Seems like reading it 5 times was not enough as well *GG*.

**Comment by sur5r** [comment]
In case this did not produce a notification: I rewrote a little more.

**Comment by Thynix** [comment]
Merged, thanks! I'll deploy it when I get more time.

**Pull request merged**
