### PR TITLE
Homepage polish

### PR DESCRIPTION
**Pull request by Thynix**
These are some changes I made at Ryan's suggestion, and some Ryan did. There are a few more changes I can add; among them are removing the SUMA award because it's old and moving the news section to the left of the top download button. I'm not sure I like the Twitter / GitHub buttons yet. Thoughts?

### CODE REVIEW

**Comment by steveatinfincia** [comment]
Looks good to me

**Comment by ArneBab** [comment]
I like the carousel, but I agree that the homepage is too cluttered and it duplicates what’s below, so I’d say go for it.

**Comment by xor-freenet** [comment]
Nice! Thanks! Conceptual ACK - would really be thankful to see this merged soon so I can build more improvements upon it. (Conceptual = Haven't read the source code, cannot justify its quality or security)

I'd also remove the Twitter / GItHub buttons, and reduce the vertical spacing next to them.
But I'd prefer this to be merged quickly if you don't have the time to do it on your own.
I'll deal with it in an upcoming PR then.

## Screenshots

### Old

website-old

### New

website-new

**Comment by Thynix** [comment]
I agree on removing the buttons. I'm hoping to get this merged once I do
that, shift the download button to the right, and put the news to the left
of that. Assuming it ends up looking okay.

**Comment by xor-freenet** [comment]
On Sunday, August 07, 2016 08:50:37 PM Steve Dougherty wrote:

> I agree on removing the buttons. I'm hoping to get this merged once I do
> that, shift the download button to the right, and put the news to the left
> of that. Assuming it ends up looking okay.

No need to remove the buttons on your own - I've already filed a pull request 
to deal with that & various other pull requests.
Before you do any further work please have a look to avoid merge/style 
conflicts.

**Pull request merged**
