### PR TITLE
faq: add entry on users facing legal trouble

### PR DESCRIPTION
**Pull request by Thynix**
As suggested by Matthew: https://emu.freenetproject.org/pipermail/devl/2015-November/038639.html

The entry reads:

> ### Has anyone ever faced legal trouble for their anonymous activities conducted on Freenet?
> 
> Yes. There is one such instance that we know of. United States law enforcement can identify anonymous users of [Freenet](http://www.thedickinsonpress.com/news/north-dakota/3885239-predators-police-online-struggle) and [Tor](http://motherboard.vice.com/read/court-docs-show-a-university-helped-fbi-bust-silk-road-2-child-porn-suspects). It is reasonable to assume that other governments have access to the same technology, which is provided by private contractors. If you are concerned about governments, you should use Freenet's capacity to connect only to users you trust, ("high" network security level or higher) and bear in mind that no anonymity technology provides perfect protection.
> 
> While we applaud law enforcement's apparent success in apprehending suspects allegedly sharing child abuse images, any security flaws they may have used are not limited to such noble usage. Many governments persecute and prosecute political dissidents for legitimate speech published online. Therefore we hope to discover and fix these flaws to protect legitimate users.

### CODE REVIEW

**Comment by ArneBab** [comment]
Maybe “Therefore we hope to discover and fix these flaws to protect those who fight for human rights, against corruption, for a peaceful future and for other legitimate goals.”?

That explicitly spells out causes worth fighting for and as such provides a positive contrast which I think is needed here (otherwise only the negative will stick, because only that has an example).

**Comment by Thynix** [comment]
Sure. It now reads:

> ### Has anyone ever faced legal trouble for their anonymous activities conducted on Freenet?
> 
> Yes. There is one such instance that we know of. United States law enforcement can identify anonymous users of [Freenet](http://www.thedickinsonpress.com/news/north-dakota/3885239-predators-police-online-struggle) and [Tor](http://motherboard.vice.com/read/court-docs-show-a-university-helped-fbi-bust-silk-road-2-child-porn-suspects). It is reasonable to assume that other governments have access to the same technology, which is provided by private contractors. If you are concerned about governments, you should use Freenet's capacity to connect only to users you trust, ("high" network security level or higher) and bear in mind that no anonymity technology provides perfect protection.
> 
> While we applaud law enforcement's apparent success in apprehending suspects allegedly sharing child abuse images, any security flaws they may have used are not limited to such noble usage. Many governments persecute and prosecute political dissidents for legitimate speech published online. Therefore we hope to discover and fix these flaws to protect those who fight for human rights, against corruption, for a peaceful future, and for other legitimate goals.

**Comment by Thynix** [comment]
It now reads:

> ### Has anyone ever faced legal trouble for their anonymous activities conducted on Freenet?
> 
> Yes. There is one such instance that we know of. United States law enforcement can identify anonymous users of [Freenet](http://www.thedickinsonpress.com/news/north-dakota/3885239-predators-police-online-struggle) and [Tor](http://motherboard.vice.com/read/court-docs-show-a-university-helped-fbi-bust-silk-road-2-child-porn-suspects). Without further information we do not know how they did this, but we suspect it affects people using "normal" or lower network security level. It is reasonable to assume that other governments have access to the same technology, which is provided by private contractors. If you are concerned about governments, you should use Freenet's capacity to connect only to users you trust, ("high" network security level or higher) and bear in mind that no anonymity technology provides perfect protection.
> 
> While we applaud law enforcement's apparent success in apprehending suspects allegedly sharing child abuse images, any security flaws they may have used are not limited to such noble usage. Many governments persecute and prosecute political dissidents for legitimate speech published online. Therefore we hope to discover and fix these flaws to protect those who fight for human rights, against corruption, for a peaceful future, and for other legitimate goals.

**Comment by Thynix** [comment]
Deployed.

**Comment by ArneBab** [comment]
Thank you!

**Pull request merged**
