### PR TITLE
Fix navbar overlay

### PR DESCRIPTION
**Pull request by bertm**
In the end, `position: sticky` did not work out quite well: anchor links did not function correctly (they aligned the anchor element with the top of the window, not below the navigation bar). To resolve that, I would have to introduce custom Javascript, which ended up to be a complete solution to this problem.

As might be obvious from the commit messages, getting the anchor links to work correctly was not quite trivial. I sure hope it works on all major browsers, but I can't test every singe one of them. This appears to work in Firefox 40, Chrome 43, and Android Chrome _whatever the version may be on my Android 4.2 phone_. All code should degrade gracefully when the browser has Javascript disabled.

Please test on your favourite browser before deploying. [Live version here](https://bertm.github.io/website/output) (EN only).

_this also somewhat reduces the horizontal spacing in the navigation header to prevent it from wrapping by default on Dutch, and strongly reduces the vertical spacing all over the website_

### CODE REVIEW

**Comment by bertm** [comment]
Since I forgot to change the stylesheet filename:

4d5e43c changes how we prevent stale caches from breaking our page: instead of changing the CSS filename on every update, we might as well use query strings. That way we only have to modify `common.py`, instead of having to alter the filename as well. To force an update, just increment the query string by one.

**Comment by Thynix** [comment]
Oh, I like the query string.

**Comment by Thynix** [comment]
Deployed, thanks!

The fonts appear larger on your demonstration site than as deployed. Any idea why that is? I think I prefer the larger fonts.

**Comment by bertm** [comment]
Thanks for merging!

As for the font size, both sites look the same here. I have no idea what makes fonts appear different for you, I don't think I have touched anything related to that.

**Pull request merged**
