### PR TITLE
Modernize file type icons

### PR DESCRIPTION
**Pull request by bertm**
This modernizes the file type icons in the Papers section. The ones used previously had a white background, which was far from aesthetically pleasing on our new black background.

Part of this change is a rewrite of the icon's image tags to use reference-style image links, so their respective file paths no longer appear in the translatable content. This will ease future updates to file locations.

### CODE REVIEW

**Comment by Thynix** [comment]
Thanks! These look good. I hope IntelliJ has a logo suitable for dark backgrounds somewhere; the [current one](https://freenetproject.org/donate.html#Sponsors) is pretty bad.

**Comment by bertm** [comment]
Thanks for merging!

As for IntelliJ, are you looking for something like this? (transparent, you might want to view it on a dark background)



I ripped it from the [SVG logo sprites](https://www.jetbrains.com/img/logos/jb-logos-sprite.svg) on their website.

**Comment by Thynix** [comment]
Yes, like that! I wasn't able to find those.

**Comment by Thynix** [comment]
Fixed in fd6bccea6b084ae0655263c5fb2423d4b99468a6 using [this](https://www.jetbrains.com/idea/docs/logo_intellij_idea.svg) from [here](https://www.jetbrains.com/company/press/materials.html#idea).

**Comment by bertm** [comment]
Looks great that way, nice find!

**Pull request merged**
